language: ruby

rvm:
  - 2.1

script: 
  - bundle exec jekyll build
  - 'bundle exec htmlproof ./_site --href-ignore "#","#top-of-page","http://www.linkedin.com/in/miloyip"'

branches:
  only:
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
